name: aphasia_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  audioplayers: ^4.0.1
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  wav: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/d4.mp3
    - assets/f4.mp3
    - assets/e4.mp3
    - assets/g4.mp3
